### ISSUE TITLE
Tempo isn't correct/accurate

### ISSUE THREAD

**Issue by currentsound** [r3mot/sampler-step#3]
This is cool. UI looks professional. I noticed a few things you can improve. 

1. Tempo is much slower than actual tempo, it's almost half the speed/bpm of what's being displayed. 

Maybe each step is playing the duration of 8th notes instead of 16ths? Either that or the tempo is displaying 120 when it's actually more like 60. So if there is no issue with the tempo that means each step takes twice as long as it should take meaning they must be 8th notes instead of 16ths resulting in a 2 bar loop instead of a 1 bar loop. 

But I don't know if the issue is with step note length or tempo display.

Are you using 16th notes? In a step sequencer, 16th notes is standard.

**Comment by r3mot** [comment]
@currentsound Thank you for the kind words and for taking the time to report this issue!

You’re absolutely right. The tempo was feeling slower because I had the step duration set to 8th notes instead of the more standard 16th notes. I’ve just pushed a fix in the latest commit, where I adjusted the step timing to 16th notes.
